#@ load("@ytt:data", "data")
#@ load("@ytt:base64","base64")
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namespace: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: external-dns
---
apiVersion: v1
kind: Secret
metadata:
  name: google-cloud-dns-key
  namespace: external-dns
data:
  key.json: #@ base64.encode(data.values.external_dns.gcp.service_account_key)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --source=service
        - #@ "--domain-filter=" + data.values.external_dns.parent_domain
        - --provider=google
        - #@ "--google-project=" + data.values.external_dns.gcp.project_id
        - --policy=upsert-only #! would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --registry=txt
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/google-cloud-dns/key.json
        volumeMounts:
        - name: google-cloud-dns-key
          mountPath: /etc/google-cloud-dns
          readOnly: true
      volumes:
      - name: google-cloud-dns-key
        secret:
          secretName: google-cloud-dns-key
