#@data/values
---

version:
  major: 0
  minor: 4
  patch: 0

#! Used by any component that has an external interface. It is used for traffic to system components of CF.
#! - usually you'll want to configure a DNS entry for *.<system_domain> to point to the cluster's external load balancer
#system_domain: system.cf.example.com

#! The root domains used for apps that are pushed to CF.
#! - you can use the same domain for system and apps if desired
app_domains:
#@overlay/append
- apps.cf.example.com

#! To push apps from source code, you need to configure the `app_registry` block
#! Example below is for docker hub. For other registry examples, see below.

app_registry:
   hostname: https://index.docker.io/v1/
   #! often times this is just your `docker_user`
   repository_prefix: <docker_hub_repository>
   username: <docker_user>
   password: <docker_password>

#! example below is for a Google container registry. Make sure to remove other registry blocks if you intend to use GCR
#! app_registry:
#!  hostname: gcr.io
#!  repository_prefix: <gcr.io/gcp_project_id/cf-workloads>
#!  username: _json_key
#!  password: |
#!    contents_of_service_account_json

#! example below is for a Azure container registry. Make sure to remove other registry blocks if you intend to use ACR
#! app_registry:
#!  hostname: <registry-name>.azurecr.io
#!  repository_prefix: <registry-name>.azurecr.io
#!  username: <username>
#!  password: <password>
