#@data/values
---
#! The password for the CF "admin" user.
#! - operators can use the admin user to test `cf push`
cf_admin_password: cfadminpassword

#! The blobstore secret key shared between CAPI and the blobstore.
cf_blobstore:
  secret_key: the_blobstore_secret_key

#! The admin password for operators to access the database.
cf_db:
  admin_password: the_cf_dbadmin_password

#! The db password shared between CAPI and the database.
capi:
  database:
    password: ccdb_password

#! Notes about X.509 certificates:
#! - the certificates and keys are base64 encoded
#! - all of the certs should have KeyUsage that includes server and client authentication

#! certificate, private key, and certificate authority used to identify the CF installation (i.e. the ingress gateway).
#! - should be valid for *.system.cf.example.com
system_certificate:
  crt: ingress_gateway_certificate
  key: ingress_gateway_private_key
  ca: ingress_gateway_certificate_ca

#! certificate, private key, and certificate authority used to identify the CF installation (i.e. the ingress gateway).
#! - should be valid for *.apps.cf.example.com
#! - may be the system cert, as long as the system cert is valid for the apps domain as well
workloads_certificate:
  crt: workload_certificate
  key: workload_private_key
  ca: workload_certificate_ca

#! certificate, private key, and certificate authority used internally within the CF installation (i.e. cf-system.svc.cluster.local).
#! - should be valid for *.cf-system.svc.cluster.local
internal_certificate:
  crt: &crt internal_certificate
  key: &key internal_private_key
  ca: internal_certificate_ca

#! Log Cache CA certificate and private key
#! - the common name needs to be log-cache-ca
log_cache_ca:
  crt: log_cache_ca_certificate
  key: log_cache_ca_private_key

#! Certificate and private key for the Log Cache server
#! - these are used for both server and client mTLS interactions within Log Cache
#! - the common name needs to be log-cache
log_cache:
  crt: log_cache_certificate
  key: log_cache_private_key

#! Certificate and private key for the metrics component of Log Cache
#! - these are used for both server and client mTLS interactions within Log Cache
#! - the common name needs to be log-cache-metrics
log_cache_metrics:
  crt: log_cache_metrics_certificate
  key: log_cache_metrics_private_key

#! Certificate and private key for the gateway component of Log Cache
#! - these are used for both server and client mTLS interactions within Log Cache
#! - the common name needs to be log-cache-gateway
#! - the alternative_names list should include localhost
log_cache_gateway:
  crt: log_cache_gateway_certificate
  key: log_cache_gateway_private_key

#! Certificate and private key for the syslog component of Log Cache
#! - these are used for both server and client mTLS interactions within Log Cache
#! - the common name needs to be log-cache-syslog
log_cache_syslog:
  crt: log_cache_syslog_certificate
  key: log_cache_syslog_private_key

metric_proxy:
  ca:
    crt: *crt
    key: *key
  cert:
    #! This certificate should be valid for metric-proxy.cf-system.svc.cluster.local
    crt: *crt
    key: *key

uaa:
  database:
    #! The db password shared between UAA and the database.
    password: uaadb_password
  #! The secret used for the UAA admin client.
  admin_client_secret: uaaadminclientsecret
  #! JWT policy configuration
  jwt_policy:
    #! This private key should NOT be base64 encoded
    signing_key: jwt_policy_signing_key
  #! Encyption key for encrypting data stored in the database
  encryption_key:
    passphrase: encryption_key_passphrase
