#@ load("@ytt:assert", "assert")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("postgres.star", "cfdb_enabled")

#@ def add_cf_db_namespace():
#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: cf-db
#@ end

#@ if cfdb_enabled():
---
apiVersion: v1
kind: Namespace
metadata:
  name: cf-db
  labels:
    name: cf-db

---
apiVersion: v1
kind: Secret
metadata:
  name: cf-db-admin-secret
  namespace: cf-db
data:
  #@ if len(data.values.cf_db.admin_password) == 0:
  #@  assert.fail("cf_db.admin_password cannot be empty")
  #@ end
  postgresql-password: #@ base64.encode(data.values.cf_db.admin_password)

---
apiVersion: v1
kind: Secret
metadata:
  name: cf-db-credentials
  namespace: cf-db
data: {}

--- #@ template.replace(overlay.apply(library.get("postgres").eval(), add_cf_db_namespace()))
#@ end
